#!/bin/bash

yum -y install php php-xml

cd /tmp
rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
yum -y remove php-common-5.3.3-40.el6_6.x86_64
yum -y install php55w php55w-opcache

yum -y install php55w-xml php55w-mcrypt php55w-gd php55w-devel php55w-mysql php55w-mbstring

vi /etc/php.ini
memory_limit = 512M

cd /tmp
wget http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm
rpm -ivh mysql-community-release-el6-5.noarch.rpm
yum -y install mysql-server

service mysqld start

mysql_secure_installation

mysql -u root -p 
#Enter the remaining commands at the mysql> prompt.

create database magento;
GRANT ALL ON magento.* TO magento@localhost IDENTIFIED BY 'magento';


cd /usr/share/nginx/html

clear

sudo /etc/init.d/mysqld restart

sudo /usr/bin/mysql_secure_installation

stty erase '^?'
    
echo -n "Database Name: "
read DBNAME

echo -n "Database User: "
read DBUSER

echo -n "Database Password: "
read DBPASS

echo -n "Admin Password: "
read ADMIN_PASS

echo -n "Store URL (with trailing slash): "
read URL

echo -n "Include Sample Data? [Y/n] "
read SAMPLE_DATA

    echo
    echo "Now installing Magento with sample data..."
    
    echo
    echo "Downloading packages..."
    echo
    
    wget https://s3-eu-west-1.amazonaws.com/magento-installer19/magento-1.9.1.0.tar.gz
    wget https://s3-eu-west-1.amazonaws.com/magento-installer19/magento-sample-data-1.9.0.0.tar.gz
    
    echo
    echo "Extracting data..."
    echo
    
    tar xf magento-1.9.1.0.tar.gz
    tar xf magento-sample-data-1.9.0.0.tar.gz
    
    echo
    echo "Moving files..."
    echo
    
    mv magento-sample-data-1.9.0.0/media/* magento/media/
    mv magento-sample-data-1.9.0.0/magento_sample_data_for_1.9.0.0.sql magento/data.sql
    mv magento/* magento/.htaccess .
    
    echo
    echo "Setting permissions..."
    echo
    
    chmod +x mage
    
    echo
    echo "Importing sample products..."
    echo
    
    mysql -h localhost -u $DBUSER -p$DBPASS $DBNAME < data.sql
    
    echo
    echo "Initializing PEAR registry..."
    echo
    
    chmod u+x mage 
    ./mage mage-setup .
    ./mage config-set preferred_state stable`
    
    echo
    echo "Installing core extensions..."
    echo
    
    ./mage install http://connect20.magentocommerce.com/community Mage_All_Latest --force
    
    echo
    echo "Refreshing indexes..."
    echo
    
    /usr/bin/php -f shell/indexer.php reindexall
    
    echo
    echo "Cleaning up files..."
    echo
    
    rm -rf magento/ magento-sample-data-1.9.0.0/
    rm -rf magento-1.9.1.0.tar.gz magento-sample-data-1.9.0.0.tar.gz
    rm -rf *.sample *.txt data.sql
    
    echo
    echo "Installing Magento..."
    echo
    
    /usr/bin/php -f install.php -- \
    --license_agreement_accepted "yes" \
    --locale "en_US" \
    --timezone "America/Phoenix" \
    --default_currency "USD" \
    --db_host "localhost" \
    --db_name "$DBNAME" \
    --db_user "$DBUSER" \
    --db_pass "$DBPASS" \
    --url "$URL" \
    --use_rewrites "yes" \
    --use_secure "no" \
    --secure_base_url "" \
    --use_secure_admin "no" \
    --admin_firstname "Store" \
    --admin_lastname "Owner" \
    --admin_email "email@address.com" \
    --admin_username "admin" \
    --admin_password "$ADMIN_PASS"
    
    echo
    echo "Finished installing the latest stable version of Magento with Sample Data"
    echo
    
    echo "+=================================================+"
    echo "| MAGENTO LINKS"
    echo "+=================================================+"
    echo "|"
    echo "| Store: $URL"
    echo "| Admin: ${URL}admin/"
    echo "|"
    echo "+=================================================+"
    echo "| ADMIN ACCOUNT"
    echo "+=================================================+"
    echo "|"
    echo "| Username: admin"
    echo "| Password: $ADMIN_PASS"
    echo "|"
    echo "+=================================================+"
    echo "| DATABASE INFO"
    echo "+=================================================+"
    echo "|"
    echo "| Database: $DBNAME"
    echo "| Username: $DBUSER"
    echo "| Password: $DBPASS"
    echo "|"
    echo "+=================================================+"
    
		service php-fpm restart
    service nginx restart

    exit
